name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        deno: ["v1.x", "nightly"]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2.2.0
        with:
          deno-version: ${{ matrix.deno }}

      - name: Deno Version
        run: deno --version
      
      - name: Cache Dependencies
        run: deno cache deps_test.ts

      - name: Run Tests
        run: deno test -A --unstable
